common: &common
  domain_url: <%= ENV.fetch('DOMAIN_URL') %>

development:
  <<: *common
  secret_key_base: <% ENV.fecth('SECRET_KEY_BASE') %>

test:
  <<: *common
  secret_key_base: <% ENV.fetch('SECRET_KEY_BASE') %>

staging:
  <<: *common
  secret_key_base: <% ENV.fetch('SECRET_KEY_BASE') %>

production:
  <<: *common
  secret_key_base: <% ENV.fetch('SECRET_KEY_BASE') %>
