common: &common
  domain_xx: <%= ENV.fetch('DOMAIN_URL') %>
  domain_url: <%= ENV.fetch('DOMAIN_URL') %>

development:
  <<: *common
  secret_key_base: 'development_seed'

test:
  <<: *common
  secret_key_base: 'test_seed'

staging:
  <<: *common
  secret_key_base: <% ENV.fetch('SECRET_KEY_BASE') %>

production:
  <<: *common
  secret_key_base: <% ENV.fetch('SECRET_KEY_BASE') %>
