common: &common
  domain_url: <%= ENV.fetch('DOMAIN_URL') %>
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
